[package]
name = "physics_lab"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_egui = "0.27.1"
bevy_rapier2d = { version = "0.26.0", features = ["simd-stable"] }
rand = "0.8.5"

[profile.dev.package."*"]
opt-level = 3